#21 создал простые круды для датасетов, environment-ов и It-service-ов, без связок
Amaralus/no-code-qa-platform pull request #25
Opened 2023-10-27 19:44 UTC by serezakorotaev

2023-10-28 13:11 UTC, runafterasun approved these changes

2023-10-29 10:37 UTC, Amaralus requested changes

2023-10-29 10:37 UTC, Amaralus commented on src/main/java/apps/amaralus/qa/platform/ErrorHandler.java
> +    @ExceptionHandler(EntityNotFoundException.class)
это не правильно кидать 404 если нет сущности просто для поиска, лучше отдавать no content, 404 нужен только когда нет сущности к критическом случае например prime/{A}/secondary/{B} и не нашли A, а если нет B то no content и в других подобных случаях когда можно считать, что если нет сущности, то это именно ошибка, а не часть нормального поведения

2023-10-29 10:37 UTC, Amaralus commented on src/main/java/apps/amaralus/qa/platform/environment/EnvironmentController.java
> +    @PatchMapping("/{id}")
если ты меняешь все то это пут, а не патч, патч для изменения конкретного поля, см контроллер проектов

2023-10-29 10:37 UTC, Amaralus commented on src/main/java/apps/amaralus/qa/platform/environment/EnvironmentService.java
> +    public EnvironmentModel updateEnvironment(Long id, Environment environment) {
здесь надо подумать с точки зрения фронта и того какие могут быть модификации, я лично не уверен что надо обновлять все за раз, хз

2023-10-29 12:39 UTC, serezakorotaev commented on src/main/java/apps/amaralus/qa/platform/ErrorHandler.java
> +    @ExceptionHandler(EntityNotFoundException.class)
хэндлер для случая если при создании какой-либо сущности указывается не существующий проект. как раз подходит под твой пример

2023-10-29 12:40 UTC, serezakorotaev commented on src/main/java/apps/amaralus/qa/platform/environment/EnvironmentController.java
> +    @PatchMapping("/{id}")
Да, в целом, в моем случае получилось что меняю все, поправлю

2023-10-29 12:41 UTC, serezakorotaev commented on src/main/java/apps/amaralus/qa/platform/environment/EnvironmentService.java
> +    public EnvironmentModel updateEnvironment(Long id, Environment environment) {
можно сказать что пока просто набросок, будем наверное в будущем прорабатывать? если что, сейчас могу действительно подделать все под патч и изменять только описание environment

2023-10-29 12:50 UTC, serezakorotaev commented on src/main/java/apps/amaralus/qa/platform/environment/EnvironmentController.java
> +    @PatchMapping("/{id}")
ну хотя по сути, при обновлении, можно будет же передать только конкретные поля, а не переданные оставить такими же. Это же вписывается под патч, когда меняется частично поля, а не происходит полностью замена

2023-10-31 09:36 UTC, Amaralus approved these changes
Предлагаю обсудить как будет выглядеть дизайн страниц на фронте и продумать их функциональность, а после уже делать под это, сейчас апрув

2023-10-31 09:37 UTC, Amaralus commented
Перед мержем подними версию в пом и в докер компосе на 0.0.1 плз

2023-10-31 14:27 UTC, merged