36 сделал базовые плейсхолдеры и возможность подстановки пользовательских плейсхолдеров в различные property
Amaralus/no-code-qa-platform pull request #38
Opened 2023-11-20 16:51 UTC by serezakorotaev

2023-11-20 16:55 UTC, serezakorotaev commented
Пример:

```
{
    "id": 5,
    "name": "thrid dataset",
    "alias": "folder#6",
    "description": "thrid dataset description",
    "project": "first project",
    "variables": {
        "text": "no-code project",
        "sentense": "our {{text}}",
        "thrid": "{{sentense}} test {{uuid}}"
    }
}
```

По запросу /api/placeholders?placeholder=folder#6:thrid&project=first project (найти плейсхолдер проекта по алиасу), получим готовый плейсхолдер
`our no-code project test cec04a53-5e92-486f-abeb-989a25c84164`

2023-11-20 16:56 UTC, serezakorotaev commented
resolve #36 #37

2023-11-26 09:58 UTC, Amaralus requested changes
не все доглядел, давай созвонимся и обсудим, мне кажется есть какие-то пробелы в ux

2023-11-26 10:05 UTC, serezakorotaev commented on src/main/java/apps/amaralus/qa/platform/placeholder/enums/Placeholder.java
> +    WORD {
Да согласен, у меня было представление потом допереть это до нормального слова)

2023-12-12 10:02 UTC, Amaralus requested changes
чисто придирка: 
давай в GenericMapper или как там его назовем методы просто map чтобы выглядело красиво и буквы не смущали в названии, так поправить что указал, поднять версию и можно вливать будет

2023-12-12 15:43 UTC, Amaralus approved these changes

2023-12-12 15:46 UTC, merged