49 save report
Amaralus/no-code-qa-platform pull request #53
Opened 2024-04-21 12:22 UTC by serezakorotaev

2024-04-21 12:25 UTC, serezakorotaev commented on src/main/java/apps/amaralus/qa/platform/runtime/report/TestReportService.java
> +    private final ReportMapper reportMapper;
получается три модельки для отчета - Report, TestReportModel, TestReport. Т.е одна собирает отчет наружу, другая это представление бд, третья собирает отчет внутри для бд. Нормально ли такое разделение по моделькам?

2024-04-25 08:02 UTC, Amaralus requested changes

2024-04-25 08:02 UTC, Amaralus commented on src/main/java/apps/amaralus/qa/platform/runtime/report/TestReportModel.java
> +    public record TestSubReport(
вынеси отдельно и назови это как модель

2024-04-25 08:02 UTC, Amaralus commented on src/main/java/apps/amaralus/qa/platform/runtime/execution/ExecutableTestPlan.java
> +import java.time.LocalTime;
лишний импорт

2024-04-25 08:02 UTC, Amaralus commented on src/main/java/apps/amaralus/qa/platform/runtime/ExecutionManager.java
> +        testReportService.create(report, testPlan.getTestInfo());
задание контекста приложение должно быть на строке 69, не смог поставить комент выше

2024-04-28 15:23 UTC, Amaralus requested changes

2024-04-28 15:23 UTC, Amaralus commented on src/main/java/apps/amaralus/qa/platform/testplan/report/TestReport.java
> +    private final ZonedDateTime startTime = ZonedDateTime.now();
это не правильно, время старта это когда менеджер вызвал execute у тестплана, соответсвенно это нужно добавить и брать из тестплана

2024-04-29 12:10 UTC, merged